const ITEM_MASTER = [
  {
    code: "0001",
    name: "Premium Butter Cake",
    weight: "280 g",
    price: 16500,
    category: "Fresh Cake",
    subcategory: "Premium Cakes",
  },
  {
    code: "0002",
    name: "Premium Marble Cake",
    weight: "280 g",
    price: 16500,
    category: "Fresh Cake",
    subcategory: "Premium Cakes",
  },
  {
    code: "0003",
    name: "Premium Butter Dry Cake",
    weight: "250 g",
    price: 20000,
    category: "Dry Cake",
    subcategory: "Premium Dry Cakes",
  },
  {
    code: "0004",
    name: "Premium Marble Dry Cake",
    weight: "250 g",
    price: 20000,
    category: "Dry Cake",
    subcategory: "Premium Dry Cakes",
  },
  {
    code: "0005",
    name: "Premium Butter Cookie 15 g/ 17 g",
    weight: "150 g/ 170 g",
    price: 15500,
    category: "Cookies",
    subcategory: "Premium Cookies",
  },
  {
    code: "0006",
    name: "Premium Cashew Nuts Cookie 15 g/ 17 g",
    weight: "150 g",
    price: 15500,
    category: "Cookies",
    subcategory: "Premium Cookies",
  },
  {
    code: "0007",
    name: "Premium Chocolate Chip Cookie 15 g/ 17 g",
    weight: "150 g/ 170 g",
    price: 18500,
    category: "Cookies",
    subcategory: "Premium Cookies",
  },
  {
    code: "0008",
    name: "Premium Tea Cookie",
    weight: "",
    price: 0,
    category: "Cookies",
    subcategory: "Premium Cookies",
  },
  {
    code: "0009",
    name: "Premium Coffee Cookie",
    weight: "",
    price: 0,
    category: "Cookies",
    subcategory: "Premium Cookies",
  },
  {
    code: "0010",
    name: "Cashew Nuts Cookie (Double)",
    weight: "240 g",
    price: 9500,
    category: "Cookies",
    subcategory: "Double Cookies",
  },
  {
    code: "0011",
    name: "Chocolate Chip Cookie (Double)",
    weight: "240 g",
    price: 9500,
    category: "Cookies",
    subcategory: "Double Cookies",
  },
  {
    code: "0012",
    name: "Oil Cake",
    weight: "250 g",
    price: 8000,
    category: "Fresh Cake",
    subcategory: "Standard Cakes",
  },
  {
    code: "0013",
    name: "Chocolate Oil Cake",
    weight: "250 g",
    price: 8500,
    category: "Fresh Cake",
    subcategory: "Standard Cakes",
  },
  {
    code: "0014",
    name: "Rose Cake",
    weight: "250 g",
    price: 8500,
    category: "Fresh Cake",
    subcategory: "Standard Cakes",
  },
  {
    code: "0015",
    name: "Dry Cake_Oil Dry Cake",
    weight: "180 g",
    price: 8500,
    category: "Dry Cake",
    subcategory: "Standard Dry Cakes",
  },
  {
    code: "0016",
    name: "Chocolate Dry Cake",
    weight: "180 g",
    price: 9500,
    category: "Dry Cake",
    subcategory: "Standard Dry Cakes",
  },
  {
    code: "0017",
    name: "Rose Dry Cake",
    weight: "180 g",
    price: 9500,
    category: "Dry Cake",
    subcategory: "Standard Dry Cakes",
  },
  {
    code: "0018",
    name: "Coconut Raisin Cookie",
    weight: "200 g",
    price: 13500,
    category: "Cookies",
    subcategory: "Nut Cookies",
  },
  {
    code: "0019",
    name: "Macadamia Cookie",
    weight: "200 g",
    price: 13500,
    category: "Cookies",
    subcategory: "Nut Cookies",
  },
  {
    code: "0020",
    name: "Walnut Cookie",
    weight: "200 g",
    price: 13500,
    category: "Cookies",
    subcategory: "Nut Cookies",
  },
  {
    code: "0021",
    name: "Butter Cookie",
    weight: "200 g",
    price: 12000,
    category: "Cookies",
    subcategory: "Middle Cookies",
  },
  {
    code: "0022",
    name: "Chocolate Cookie",
    weight: "200 g",
    price: 12000,
    category: "Cookies",
    subcategory: "Middle Cookies",
  },
  {
    code: "0023",
    name: "Coffee Cookie",
    weight: "200 g",
    price: 12000,
    category: "Cookies",
    subcategory: "Middle Cookies",
  },
  {
    code: "0024",
    name: "Tea Cookie",
    weight: "200 g",
    price: 12000,
    category: "Cookies",
    subcategory: "Middle Cookies",
  },
  {
    code: "0025",
    name: "Cashew Nuts Cookie (Combo)",
    weight: "960 g",
    price: 27500,
    category: "Cookies",
    subcategory: "Double Cookies",
  },
  {
    code: "0026",
    name: "Chocolate Chip Cookie (Combo)",
    weight: "960 g",
    price: 27500,
    category: "Cookies",
    subcategory: "Double Cookies",
  },
  {
    code: "00049SC",
    name: "Chocolate Cookie 170 G",
    weight: "170 g",
    price: 9000,
    category: "Cookies",
    subcategory: "OEM Cookies",
  },
  {
    code: "00050SC",
    name: "Butter Cookie 170 G",
    weight: "170 g",
    price: 9000,
    category: "Cookies",
    subcategory: "OEM Cookies",
  },
  {
    code: "007",
    name: "Premium Earl Grey Cookie",
    weight: "",
    price: 0,
    category: "Cookies",
    subcategory: "Premium Cookies",
  },
];
